n = 10

set.seed(1)
x = factor(rep(c(1,2), each = n/2))
y = vector("numeric", length = n)
y[x==1]<-sample(1:k,n/2,replace=TRUE,prob=probs1)
y[x==2]<-sample(1:k,n/2,replace=TRUE,prob=probs2)
simdata1 = list("x"= x,"y" = y)
r1 = run_methods_fct(y = simdata1$y, x = simdata1$x)

set.seed(1)
x = factor(rep(c(1,2), each = n/2))
y = vector("numeric", length = n)
y[x==1]<-sample(1:k,n/2,replace=TRUE,prob=probs1)
y[x==2]<-sample(1:k,n/2,replace=TRUE,prob=probs2)
y = factor(y, ordered = TRUE)
simdata2 = list("x"= x,"y" = y)
r2 = run_methods_fct(y = simdata2$y, x = simdata2$x)

set.seed(1)
x = factor(rep(c(1,2), each = n/2))
y = vector("numeric", length = n)
y[x==1]<-sample(1:k,n/2,replace=TRUE,prob=probs1)
y[x==2]<-sample(1:k,n/2,replace=TRUE,prob=probs2)
y = factor(y)
simdata3 = list("x"= x,"y" = y)
r3 = run_methods_fct(y = simdata3$y, x = simdata3$x)

set.seed(1)
x = rep(c(1,2), each = n/2)
y = vector("numeric", length = n)
y[x==1]<-sample(1:k,n/2,replace=TRUE,prob=probs1)
y[x==2]<-sample(1:k,n/2,replace=TRUE,prob=probs2)
simdata4 = list("x"= x,"y" = y)
r4 = run_methods_fct(y = simdata4$y, x = simdata4$x)

set.seed(1)
x = factor(rep(c(1,2), each = n/2))
y = vector("numeric", length = n)
y[x==1]<-sample(1:k,n/2,replace=TRUE,prob=rev(probs1))
y[x==2]<-sample(1:k,n/2,replace=TRUE,prob=rev(probs2))
simdata5 = list("x"= x,"y" = y)
r5 = run_methods_fct(y = simdata5$y, x = simdata5$x)


all.equal(r1,r2)
all.equal(r1,r3)
all.equal(r1,r4)
all.equal(r1,r5)
